version: 'latest'

services:
  books: 
    container_name: "books-search"
    image: "books-search"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
